In [1]:
import gait3d

In [2]:
test_positions = camera_calibration.TestPositionsGroundTruth()

In [5]:
test_positions.add_new_marker_id(marker_id='Schraube1_unten', other_marker_ids_with_distances=[('Schraube1_Mutter', 6), ('maze_corner_open_left', 19)])

In [6]:
test_positions.unique_marker_ids

['maze_corner_open_left',
 'maze_corner_open_right',
 'maze_corner_closed_right',
 'maze_corner_closed_left',
 'Schraube1_unten',
 'Schraube1_Mutter']

In [1]:
import numpy as np

In [2]:
hund = np.asarray([1, 2, 3,4 ])

In [3]:
dogs = []
for i in range(5):
    dogs.append(hund)

In [4]:
cats = list(hund) * 5

In [5]:
cats == dogs

False

In [7]:
dogs

[array([1, 2, 3, 4]),
 array([1, 2, 3, 4]),
 array([1, 2, 3, 4]),
 array([1, 2, 3, 4]),
 array([1, 2, 3, 4])]

In [6]:
cats

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [7]:
test_positions.marker_ids_with_distances

{'maze_corner_open_left': {'maze_corner_open_right': 4,
  'maze_corner_closed_right': 50.15974481593781,
  'maze_corner_closed_left': 50,
  'Schraube1_unten': 19},
 'maze_corner_open_right': {'maze_corner_open_left': 4,
  'maze_corner_closed_right': 50,
  'maze_corner_closed_left': 50.15974481593781},
 'maze_corner_closed_right': {'maze_corner_open_left': 50.15974481593781,
  'maze_corner_open_right': 50,
  'maze_corner_closed_left': 4},
 'maze_corner_closed_left': {'maze_corner_open_left': 50,
  'maze_corner_open_right': 50.15974481593781,
  'maze_corner_closed_right': 4},
 'Schraube1_unten': {'Schraube1_Mutter': 6, 'maze_corner_open_left': 19},
 'Schraube1_Mutter': {'Schraube1_unten': 6}}

In [8]:
from pathlib import Path

In [9]:
bottom_cam = camera_calibration.SingleCamDataForAnipose(cam_id = 'bottom', filepath_synchronized_calibration_video = Path('/mnt/c/Users/dsege/Downloads/OneDrive_2022-08-22/'))

In [10]:
#add_manual_test_position_marker(self, marker_id: str, x_or_column_idx: int, y_or_row_idx: int, likelihood: float, overwrite: bool=False)

In [11]:
bottom_cam.add_manual_test_position_marker(marker_id = 'maze_corner_open_left', x_or_column_idx=10, y_or_row_idx=10, likelihood=0.9999)
bottom_cam.add_manual_test_position_marker(marker_id = 'maze_corner_open_right', x_or_column_idx=10, y_or_row_idx=50, likelihood=0.9999)
bottom_cam.add_manual_test_position_marker(marker_id = 'maze_corner_closed_right', x_or_column_idx=510, y_or_row_idx=50, likelihood=0.9999)
bottom_cam.add_manual_test_position_marker(marker_id = 'maze_corner_open_closed', x_or_column_idx=500, y_or_row_idx=10, likelihood=0.9999)

In [12]:
bottom_cam.manual_test_position_marker_coords_pred

{'maze_corner_open_left': {'x': [10], 'y': [10], 'likelihood': [0.9999]},
 'maze_corner_open_right': {'x': [10], 'y': [50], 'likelihood': [0.9999]},
 'maze_corner_closed_right': {'x': [510], 'y': [50], 'likelihood': [0.9999]},
 'maze_corner_open_closed': {'x': [500], 'y': [10], 'likelihood': [0.9999]}}

In [13]:
bottom_cam.add_manual_test_position_marker(marker_id = 'maze_corner_open_closed', x_or_column_idx=510, y_or_row_idx=10, likelihood=0.9999, overwrite=True)

In [14]:
bottom_cam.manual_test_position_marker_coords_pred

{'maze_corner_open_left': {'x': [10], 'y': [10], 'likelihood': [0.9999]},
 'maze_corner_open_right': {'x': [10], 'y': [50], 'likelihood': [0.9999]},
 'maze_corner_closed_right': {'x': [510], 'y': [50], 'likelihood': [0.9999]},
 'maze_corner_open_closed': {'x': [510], 'y': [10], 'likelihood': [0.9999]}}

In [15]:
bottom_cam.save_manual_marker_coords_as_fake_dlc_output(output_filepath = Path('/mnt/c/Users/dsege/Downloads/'))

Your dataframe was successfully saved at: /mnt/c/Users/dsege/Downloads/bottom_manual_test_position_marker_fake.h5.
Your "fake DLC marker perdictions" were successfully loaded to the SingleCamDataForAnipose object!


In [16]:
bottom_cam.validate_test_position_marker_ids(test_positions_ground_truth=test_positions)

The following marker_ids were missing and added to the dataframe with a likelihood of 0: ['maze_corner_closed_left', 'Schraube1_unten', 'Schraube1_Mutter'].
The following marker_ids were deleted from the dataframe, since they were not present in the ground truth: ['maze_corner_open_closed'].


In [17]:
bottom_cam.test_position_markers_df

scorer    manually_annotated_marker_positions                 \
bodyparts               maze_corner_open_left                  
coords                                      x   y likelihood   
0                                          10  10     0.9999   

scorer                                                                        \
bodyparts maze_corner_open_right                maze_corner_closed_right       
coords                         x   y likelihood                        x   y   
0                             10  50     0.9999                      510  50   

scorer                                                                         \
bodyparts            maze_corner_closed_left               Schraube1_unten      
coords    likelihood                       x  y likelihood               x  y   
0             0.9999                       0  0          0               0  0   

scorer                                               
bodyparts            Schraube1_Mutter                
coords    likelihood                x  y likelihood  
0                  0                0  0          0

In [18]:
 cv2.aruco.Dictionary_get(aruco.DICT_6X6_250)

In [19]:
from cv2 import aruco

In [20]:
aruco.DICT_6X6_250

10

In [23]:
type(aruco.Dictionary_get(aruco.DICT_6X6_250)) == aruco.Dictionary

True

In [26]:
use_own_intrinsic_calibration = False

In [27]:
not use_own_intrinsic_calibration

True

In [28]:
print(not use_own_intrinsic_calibration)

True


In [1]:
import numpy as np

In [15]:
ones = np.ones(10)

In [16]:
ones[np.linspace(0, 10, 5, endpoint=False, dtype=int)]

array([1., 1., 1., 1., 1.])

In [17]:
a = np.linspace(0, 10, 5, endpoint=False, dtype=int)

In [18]:
for elem in a:
    print(elem)

0
2
4
6
8


In [20]:
list(a)*5

[0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8]

In [24]:
video_filename = 'hund.mpeg'
filename = f'{video_filename[:video_filename.rfind(".")]}_intrinsic_calibration_results.p'
filename

'hund_intrinsic_calibration_results.p'

In [5]:
a = False
b = False

In [6]:
if (not a) & (not b):
    print('both are false!')

both are false!


In [7]:
hund = {'hund': 8, 'katze': (19, 20)}

In [10]:
hund['hund'] = 9
hund['katze'] = ('changable', 'it is')

In [11]:
hund

{'hund': 9, 'katze': ('changable', 'it is')}

In [14]:
a = False
b = False

In [16]:
if any([hund['hund'] != 10, a, b]):
    print('something was true')

something was true


In [2]:
from cv2 import undistort

from gait3d.utils import plot_single_frame_of_video